workflows:
  ios-build:
    name: iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
    scripts:
      - name: Disable iOS Swift Package Manager and Get dependencies
        script: |
          flutter config --no-enable-ios-swift-package-manager
          flutter pub upgrade
      - name: Build iOS App (Unsigned Debug)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
